### ISSUE TITLE
Alumni feed module, inconsistent data reference in query strings.

### ISSUE THREAD

**Issue by techmantonio** [howard-university-web-services/howard_paragraphs#4]
Was looking at line 101 vs line 103 in this file.
https://github.com/howard-university-web-services/howard_paragraphs/blob/8.x-1.x/modules/hp_alumni_feed/hp_alumni_feed.module

Question, is the correct query string reference:
*&filter[classification]=iconic_alumni*
or
*&filter[classification][value]=iconic_alumni*
?

Saw the inconsistency and was not sure if there would be an issue for the *else* case.

**Comment by drogers98** [comment]
Good eye! Its actually by design though, the [value] is only needed when providing further parameters, such as operator, ie:

"&filter[classification][value]=iconic_alumni&filter[classification][operator]=!="

If not provided, it is assumed that operator is "=".
